### ISSUE TITLE
Show winner, use correct size

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/K3OpEenRij#8]
From @markwiering:

> Ik was net weer K3OpEenRij aan het spelen (de Windows-versie, 7.0, op
Kali Linux met het programma WINE), maar mij viel op dat het spel na
een tijdje zei "Winaar {Kathleen} Winnaar", terwijl ik nergens op het
scherm zag hoe Kathleen drie op een rij kreeg. Tijdens het spel viel
mij ook op dat ik na een tijdje de zetten van de andere twee spelers
(Kristel en Kathleen) niet meer kon zien, wat dus betekende dat het
spel zich buiten het speelveld plaatsvond.
>
> Kun jij het spel dusdanig wijzigen dat het niet meer mogelijk is om
buiten het zichtbare spelveeld te spelen? Want zo wordt het voor mij
onmogelijk om dit spel uit te spelen in de, zoals jij dat op jouw
website noemt, overlevingsmode. :-D

![screenshot from 2018-06-14 10-34-46](https://user-images.githubusercontent.com/2098230/41506966-9c0a9a58-7228-11e8-906d-e2e8cf2796ed.png)

![screenshot from 2018-06-14 10-47-52](https://user-images.githubusercontent.com/2098230/41506987-e416a738-7228-11e8-8548-f53696acf27a.png)

**Comment by richelbilderbeek** [comment]
Code has improved. Problem yet unsolved, will continue on 2018-06-23

**Comment by richelbilderbeek** [comment]
I think the size is correct now, thanks to [this commit](https://github.com/richelbilderbeek/ConnectThree/commit/d2e9006b506457f40d6b23644089732790f95eb7)

**Comment by richelbilderbeek** [comment]
I could not reproduce the problem with the winning three-on-a-row not being shown.

@MarkWiering, does this problem still occur with the latest fix? (note: the fix took place in `ConnectThree`, updating that repo and a recompile yields the newest version)

**Comment by markwiering** [comment]
Does it have to be Windows? Because I am using Kali Linux right now.
If I have to compile this on Windows, then what compiler am I supposed to install for that?

**Comment by richelbilderbeek** [comment]
K3OpEenRij can be built on any OS. On Kali Linux, this is hard though, as you will also need to build the dependencies. I will continue working on a new Windows executable...

~~The `.travis.yml` is an automated build script. Running these lines in a terminal (must be done manually I am afraid) should an equally successful build.~~

~~As a special favour, this should do it:~~

```
cd K3OpEenRij
sudo apt-get install -qq g++-5
sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
./download_other_githubs
qmake K3OpEenRijDesktop.pro
make debug
./K3OpEenRijDesktop
``` 

~~Oops, I am wrong: Kali Linux has very limited packages.~~

**Comment by markwiering** [comment]
[Report: installing K3OpEenRij does NOT work!](https://pp.userapi.com/c824503/v824503498/173171/9U94o7XzMH0.jpg)
I will be waiting for the Windows executable on http://richelbilderbeek.nl/GameK3OpEenRij.htm :-D

**Comment by richelbilderbeek** [comment]
Thanks for the report. It shows you forgot to run `./download_other_githubs`, as it cannot find the repositories K3OpEenRij relies on. Try running `./download_other_githubs` and possibly you will succeed :+1:

**Comment by markwiering** [comment]
[Still does not work!](https://pp.userapi.com/c848736/v848736567/1190e/7PJ_YQqCylY.jpg)

**Comment by markwiering** [comment]
[The program runs, but I cannot start the game. The console is giving me errors whenever I click "Begin spel" or any other button. Only the button "Stoppen" works.](https://pp.userapi.com/c849132/v849132567/12323/wwWTFUAoLuM.jpg)

There is also another thing. Someone implemented the male version of K3. I can also choose a character that is not Kathleen, Kristel or Karen, nor Josje, Klaasje, Marthe or Hanne. Who are those people anyway?

**Comment by richelbilderbeek** [comment]
Congrats, you just built K3OpEenRij on Kali.

I have an idea why the game does not start.

Who the men are, I do not know. I let a girl pick these, and they are famous men apparently.

**Comment by richelbilderbeek** [comment]
Wine version has the same problem of no pop-up. Planned to fix this at 2018-07-07.

**Comment by richelbilderbeek** [comment]
@markwiering : I have tested the game to work under Linux and Windows (you can download the Windows exes [here](http://richelbilderbeek.nl/K3OpEenRij.zip)).

If there is still something wrong that is not already an Issue, feel encouraged to let me know. Else I will close this Issue in/after August 1st 2018.

**Comment by markwiering** [comment]
[Het spel werkt naar behoren! :-D ](https://pp.userapi.com/c834101/v834101253/17c45f/NhVCai1a-8c.jpg)

**Comment by richelbilderbeek** [comment]
Thanks @markwiering for the bug report and confirmation that is has been fixed :+1:
